# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  catalog.db:
    image: mongo
    container_name: "development.catalog.db"
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "mongo_data:/data/db"
volumes:
  mongo_data: